{% set name = "coin-or-cgl" %}
{% set version = "0.60.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/coin-or/Cgl/archive/releases/{{ version }}.tar.gz
  sha256: 5a2e7ca380425b3d7279d0759c625a367d06ec8293698b59f82fae38ae5df64e

build:
  number: 0
  skip: true  # [blas_impl != "openblas"]
  run_exports:
    - {{ pin_subpackage(name, min_pin='x.x', max_pin='x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - make  # [unix]
  host:
    - coin-or-utils 2.11.6
    - coin-or-osi 0.108.7
    - coin-or-clp 1.17.7
    - zlib
    - bzip2
    - openblas {{ openblas }}         # [blas_impl == "openblas"]
  run:
    - ncurses
    - readline
    - libopenblas                     # [blas_impl == "openblas"]
  # To stop the compiler pulling in an openmp implementation itself
    - _openmp_mutex                   # [linux]
  run_constrained:
    - coincbc * *_metapackage

test:
  commands:
    - test -f $PREFIX/lib/libCgl${SHLIB_EXT}
    - test -f $PREFIX/include/coin/CglAllDifferent.hpp

about:
  home: https://github.com/coin-or/Cgl
  dev_url: https://github.com/coin-or/Cgl
  doc_url: https://coin-or.github.io/Cgl/Doxygen/
  license: EPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: COIN-OR Cut Generation Library (Cgl)
  description: |
    The COIN-OR Cut Generation Library (Cgl) is a collection of cut generators
    that can be used with other COIN-OR packages that make use of cuts, such as,
    among others, the linear solver Clp or the mixed integer linear programming
    solvers Cbc or BCP. Cgl uses the abstract class OsiSolverInterface (see Osi)
    to use or communicate with a solver. It does not directly call a solver.

extra:
  recipe-maintainers:
    - wolfv
    - tkralphs
